---

- name: restart nginx 
  service: name=nginx state=restarted

- name: restart tftpd-hpa 
  service: name=tftpd-hpa state=restarted

- name: restart isc-dhcp-server 
  service: name=isc-dhcp-server state=restarted



