---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: craete container
    docker_container:
      name: caler
      hostname: caler
      image: debian:8.7
      state: started
      command: ["sleep", "600"]
  
  - name: add container to inventory
    add_host: name=caler ansible_connection=docker
    changed_when: false
  
  - name: install python
    delegate_to: caler
    raw: 'apt-get update && apt-get install -y python'

  - name: run command
    delegate_to: caler
    command: ps -ef
