---
- name: install aptitude
  apt: name=aptitude state=present

- name: install vim
  apt: update_cache=yes cache_valid_time=600 name=vim state=latest
  become: yes

- name: sshd config
  copy: src=sshd_config dest=/etc/ssh/sshd_config mode=0644
  become: yes
  notify:
  - restart sshd
  tags:
    - ssh

- name: see if root has public key for ssh
  stat: path=/root/.ssh/id_rsa.pub get_md5=false
  register: ssh_key_file
  delegate_to: 127.0.0.1

- name: generate ssh keys for root
  user: name=root generate_ssh_key=yes
  become: yes
  when: not ssh_key_file.stat.exists
  delegate_to: 127.0.0.1

- name: deploy ssh keys
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
  tags:
    - ssh
